using System.Text;
using System.Text.Json;

namespace FluentAas.ModelGeneration;

internal static class SubmodelGenerator
{
    public static void GenerateElementMembers(
        StringBuilder sb,
        JsonElement   elementsArray,
        string        indent,
        string        nestedTypePrefix,
        ref bool      usesLocalizedText)
    {
        foreach (var element in elementsArray.EnumerateArray())
        {
            if (!element.TryGetProperty("idShort", out var idShortProp))
                continue;

            var idShort      = idShortProp.GetString() ?? "Unnamed";
            var propertyName = JsonContent.ToPascalCase(idShort);

            var modelType = element.TryGetProperty("modelType", out var mt)
                                ? mt.GetString() ?? "Property"
                                : "Property";

            var cardinality = JsonContent.GetCardinality(element);
            var isCollectionCardinality =
                string.Equals(cardinality, "OneToMany", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(cardinality, "ZeroToMany", StringComparison.OrdinalIgnoreCase);

            // semanticId (for documentation)
            string? semanticIdValue = null;
            if (element.TryGetProperty("semanticId", out var semId) &&
                semId.ValueKind == JsonValueKind.Object &&
                semId.TryGetProperty("keys", out var keysArr) &&
                keysArr.ValueKind == JsonValueKind.Array &&
                keysArr.GetArrayLength() > 0)
            {
                var key0 = keysArr[0];
                if (key0.TryGetProperty("value", out var valProp))
                {
                    semanticIdValue = valProp.GetString();
                }
            }

            sb.AppendLine();
            sb.AppendLine($"{indent}/// <summary>");
            sb.AppendLine($"{indent}/// Element '{idShort}' (modelType: {modelType}, cardinality: {cardinality}" +
                          (semanticIdValue is not null ? $", semanticId: {JsonContent.Escape(semanticIdValue)}" : "") +
                          ").");
            sb.AppendLine($"{indent}/// </summary>");

            if (string.Equals(modelType, "SubmodelElementCollection", StringComparison.OrdinalIgnoreCase))
            {
                var nestedTypeName = nestedTypePrefix + propertyName;

                // Nested type
                sb.AppendLine($"{indent}public class {nestedTypeName}");
                sb.AppendLine($"{indent}{{");

                if (element.TryGetProperty("value", out var valueArr) &&
                    valueArr.ValueKind == JsonValueKind.Array)
                {
                    GenerateElementMembers(
                                           sb,
                                           valueArr,
                                           indent + "    ",
                                           nestedTypeName + "_",
                                           ref usesLocalizedText);
                }

                sb.AppendLine($"{indent}}}");
                sb.AppendLine();

                var propType = isCollectionCardinality
                                   ? $"List<{nestedTypeName}>"
                                   : nestedTypeName + "?";

                sb.AppendLine($"{indent}public {propType} {propertyName} {{ get; set; }}");
            }
            else
            {
                var elementType = JsonContent.MapElementType(element, out var isMultiLang);
                if (isMultiLang)
                    usesLocalizedText = true;

                var typeName = isCollectionCardinality
                                   ? $"List<{elementType}>"
                                   : elementType + "?";

                sb.AppendLine($"{indent}public {typeName} {propertyName} {{ get; set; }}");
            }
        }
    }
    
    
    public static string GenerateClassSource(
        string ns,
        string className,
        string submodelIdShort,
        string submodelId,
        int version,
        int revision,
        string sourceJsonRelativePath,
        JsonElement submodelElementsArray)
    {
        var sb = new StringBuilder();
        var usesLocalizedText = false;

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// This file was generated by FluentAas.ModelGeneration.");
        sb.AppendLine("// Do not edit manually.");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Strongly-typed representation of an IDTA submodel template.");
        sb.AppendLine($"    /// Source JSON (external): {sourceJsonRelativePath}");
        sb.AppendLine($"    /// Submodel ID: {JsonContent.Escape(submodelId)}");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public class {className}");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Submodel idShort from JSON.</summary>");
        sb.AppendLine($"        public const string SubmodelIdShort = \"{JsonContent.Escape(submodelIdShort)}\";");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Submodel technical ID from JSON.</summary>");
        sb.AppendLine($"        public const string SubmodelId = \"{JsonContent.Escape(submodelId)}\";");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Semantic version major extracted from submodel id.</summary>");
        sb.AppendLine($"        public const int Version = {version};");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Semantic version minor extracted from submodel id.</summary>");
        sb.AppendLine($"        public const int Revision = {revision};");
        sb.AppendLine();

        sb.AppendLine("        // Root-level submodel elements");
        SubmodelGenerator.GenerateElementMembers(
                                                 sb,
                                                 submodelElementsArray,
                                                 indent: "        ",
                                                 nestedTypePrefix: "",
                                                 ref usesLocalizedText);

        sb.AppendLine("    }");

        if (usesLocalizedText)
        {
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Simple representation of a localized text (for MultiLanguageProperty elements).");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public record LocalizedText(string Language, string Text);");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}